apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-to-pdf-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doc-to-pdf
  template:
    metadata:
      labels:
        app: doc-to-pdf
    spec:
      containers:
        - name: doc-to-pdf-container
          image: shashwat543/doc-to-pdf-app:v2  # Ensure this points to the correct image
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
