name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Build on pushes to the main branch (adjust as needed)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub or GitHub Container Registry
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/doc-to-pdf-app:v2  .
    # Step 4: Push the Docker image to the registry
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/doc-to-pdf-app:v2  
